### ISSUE TITLE
Resource time warning

### ISSUE THREAD

**Issue by sirmarknlddr** [thers/FRFuel#19] opened 2018-04-30 09:20 UTC
Frfuel gives a resource time warning on clients since the FiveM client update.

**Comment by thers** [comment] 2018-05-03 17:39
Thanks, I'll look into it.

**Comment by TomGrobbe** [comment] 2018-05-11 11:28
> Frfuel gives a resource time warning on clients since the FiveM client update.

Is this still happening? I've not been able to reproduce this while testing...

**Comment by avery1227** [comment] 2018-05-25 20:46
I've noticed it too but rarely.

**Comment by thers** [comment] 2018-06-05 15:23
As we were unable to reproduce it, im gonna ask you guys: is it critical enough to consider this an issue? If yes then I'll keep it open and hope someday it will either reproduce under some circumstances or be gone completely :)

**Comment by avery1227** [comment] 2018-06-05 17:24
I do feel this is a larger issue on low to mid range computers. I've been notified several times since my last reply. I personally believe it has to do with all the code being ran nearly non stop while in a vehicle. Such as get and display fuel level and set new fuel level. In reality if you were unable to reproduce the issue I would recommend closing this unless someone is able to get more information.

Thanks

**Comment by thers** [comment] 2018-06-05 18:28
> I personally believe it has to do with all the code being ran nearly non stop while in a vehicle. Such as get and display fuel level and set new fuel level.

Unfortunately, this is how it works, you have to do all these things on each tick (read frame), just to keep things in order on the screen. That's how original scripts work.

What's interesting though is where exactly it can stutter.

**Comment by TomGrobbe** [comment] 2018-06-05 18:28
>I personally believe it has to do with all the code being ran nearly non stop while in a vehicle. Such as get and display fuel level and set new fuel level.

That could be the issue, however there's no way around this as you kind of need to know your fuel level when you're inside the car. Besides, drawing it on the screen needs to be ran non stop anyway.

**Comment by Sojobo** [comment] 2018-08-12 19:32
This is my most expensive resource at around 0.30ms - realistically it should be zero while outside of a vehicle.

**Comment by TomGrobbe** [comment] 2018-08-13 17:45
>This is my most expensive resource at around 0.30ms - realistically it should be zero while outside of a vehicle.

Then how do you expect the resource to know if you've entered a vehicle if it can't do any checks when the player is not inside a vehicle?

That wouldn't work. Besides, 0.3ms is very, very slight. You're not going to get much lower than that for a c# resource.

I created a testing resource and it constantly had around 0.7ms when some dependencies where loaded, and 0 Tick functions were running.

You're simply not going to achieve 0ms delays for this kind of resource.

**Closed** 2018-12-28 10:31 UTC
